Add missing dependency on commons-lang 2.6
Without this dependency, use of os-package-plugin gave the following
error:

Execution failed for task ':buildDeb'.
> Could not call SystemPackagingTask.copy() on task ':buildDeb'

due to java.lang.NoClassDefFoundError: org.apache.commons.lang.time.DateFormatUtils